### ISSUE TITLE
Export PropsType interface

### ISSUE THREAD

**Issue by polianych** [vlsergey/react-bootstrap-pagination#6]
Hello, thanks for your package. Is it possible to make export `PropsType` interface to extend the `Pagination` component using default Props?

**Comment by vlsergey** [comment]
@polianych , i've published version 3.1.0 with exported `PropsType` interface.

But i'm not sure about extending the `Pagination` component. Could you provide some example what you want to archive?

**Comment by vlsergey** [comment]
@polianych , thanks for clarification!

FYI, in version 3.2.0 i've added `firstPageValue` attribute to allow change from zero-based to one-based (or any-based) value, thus example above can be made much shorter.

**Comment by polianych** [comment]
Brilliant! Since `firstPageValue` has default value, I suggest to define it as optional propery in interface: `firstPageValue?: number;`

**Comment by vlsergey** [comment]
> I suggest to define it as optional property in interface: `firstPageValue?: number;`

it's strange that it wasn't found by test cases. Fixed, now (in 3.2.1) it's optional.
